### ISSUE TITLE
Typos on "A Complete Guide to Solana Development for Ethereum Developers"

### ISSUE THREAD

**Issue by banescusebi** [solana-foundation/solana-com#110]
## Steps To Reproduce

Go to: https://solana.com/developers/evm-to-svm/complete-guide
Scroll down to: "Solana Counter Program"

## The current behavior
See highlighted text in screenshot below
<img width="1310" alt="image" src="https://github.com/user-attachments/assets/bbd49832-ad24-40bd-b0bb-705be71a294e">

## The expected behavior

<img width="1264" alt="image" src="https://github.com/user-attachments/assets/a2aac3db-c753-4573-af78-3fce64ffe30d">

**Comment by banescusebi** [comment]
I'm found more typos while reading through this page. I'll leave them all here:
1. "When developing on Solana, the most significant difference will run into is the account model design." -> "When developing on Solana, the most significant difference **you** will run into is the account model design."
2. "you have a **struct** within the Rust **smart contract stating** `initialize_counter`." -> "you have a **function** within the Rust **program called** `initialize_counter`."
3. "Solana validators forward transactions **to up** to the following four leaders" -> "Solana validators forward transactions to the following four leaders"
4. "You can find the smart contract code by visiting a smart contract address the explorer." -> "You can find the smart contract code by visiting a smart contract address **in** the explorer."
5. "EVM primarily uses Solidity to write smart contracts, while Solana uses Rust." -> "**Ethereum developers** primarily **use** Solidity to write smart contracts, while Solana developers **use** Rust."
6. `solana program deploy <program_filepath`. -> `solana program deploy <program_filepath`**`>`**.
7. `_candidate_name` to be passed into the instruction. We can see later this is used in `seeds = [_candidate_name.as_bytes().as_ref()]`. -> `_candidate_Name` to be passed into the instruction. We can see later this is used in `seeds = [_candidate_Name.as_bytes().as_ref()]`.

**Comment by catalinred** [comment]
Thanks for the feedback, @banescusebi. I'll make sure to pass this on to the team.
