### ISSUE TITLE
Typos in "EVM vs. SVM: Accounts"

### ISSUE THREAD

**Issue by banescusebi** [solana-foundation/solana-com#114]
## Steps To Reproduce
- Go to: https://solana.com/developers/evm-to-svm/accounts 
- The `code hash` row appears twice in the table below

## The current behavior
<img width="1137" alt="image" src="https://github.com/user-attachments/assets/f7721475-1752-443d-a179-e1618f71c61d">

## The expected behavior
<img width="1128" alt="image" src="https://github.com/user-attachments/assets/688a3ca6-4594-4c79-80a9-632d62a331a1">

**Comment by banescusebi** [comment]
Question: the paragraph just below the table in the screenshot ends with a column. Is there something missing after the column (highlighted in red) or is the table above the paragraph supposed to come after it?
![image](https://github.com/user-attachments/assets/2763c240-3889-435b-9845-a5bd3972861c)

**Comment by nickfrosty** [comment]
Great catches here @banescusebi! I just pushed updated to fix these two comments.
It looks like that paragraph should have been before it.
The updates should be live as soon as the website cache is busted. 
Closing this issue now that these pages have been fixed in the CMS page
