### ISSUE TITLE
Issue with 'cargo build-sbf'

### ISSUE THREAD

**Issue by bluecryptodev** [solana-foundation/solana-com#136]
I ran this command 'cargo build-sbf'. But I got this error message.

package `solana-program v2.1.7` cannot be built because it requires rustc 1.79.0 or newer, while the currently active rustc version is 1.75.0-dev

How can I resolve this issue?

**Comment by catalinred** [comment]
@bluecryptodev  I would recommend you https://solana.stackexchange.com/ for this kind of questions.

**Comment by DevElation0x** [comment]
Please tell me you resolved this. I am using the same versions, except I managed to update rustc to 1.79.0, yet I still have an issue while using solana-program 2.1.7 to successfully install with cargo-build-sbf
