### ISSUE TITLE
Issues with filter section on, On/Off Ramp Page.

### ISSUE THREAD

**Issue by Utkarsh4517** [solana-foundation/solana-com#137]
## Steps To Reproduce
- Visit https://solana.com/solanaramp
- Try to apply some filters

## The current behavior
- The checkbox is not visible while selecting any country.
- The checkbox is not visible while selecting any payment rail.

## The expected behavior
- The checkbox should have a distinct color to ensure it is properly visible.
- A cross icon should appear in the top-right corner to close the expanded filter box.

**Comment by Utkarsh4517** [comment]
Would love to work on this.

**Comment by catalinred** [comment]
Thank you for opening up this issue @Utkarsh4517. This will be fixed via https://github.com/solana-foundation/solana-com/pull/138.
