### ISSUE TITLE
Solana white paper

### ISSUE THREAD

**Issue by benjamin890923** [solana-foundation/solana-com#22]
## Steps To Reproduce

Is this part of the solana whitepaper written correctly?
I have a feeling the it's grammatically incorrect.

![slashing](https://github.com/user-attachments/assets/21f8e068-b34d-4006-a706-a4204b0ee6c9)

**Comment by catalinred** [comment]
Thanks for the heads up @benjamin890923, we'll look into it.

**Comment by catalinred** [comment]
Quick update here - the whitepaper is locked in, and we won’t be making any more changes to it.
