### ISSUE TITLE
Add Gem Wallet to list of wallets

### ISSUE THREAD

**Issue by l0vvkey** [solana-foundation/solana-com#31]
Request to add Gem Wallet that also has support for Solana.
https://gemwallet.com/solana-wallet/

To this page:
https://solana.com/solana-wallets

**Comment by catalinred** [comment]
Would you or someone from your team be able to open a PR and submit it following the logic in [`wallet-data.js`](https://github.com/solana-foundation/solana-com/blob/main/src/data/wallets/wallet-data.js)? We can continue from there and review it. Thank you.

**Comment by l0vvkey** [comment]
Thanks. Submitted a PR
https://github.com/solana-foundation/solana-com/pull/35

**Comment by catalinred** [comment]
Closed via https://github.com/solana-foundation/solana-com/pull/35
