### ISSUE TITLE
Update on https://solana.com/rpc

### ISSUE THREAD

**Issue by giftal** [solana-foundation/solana-com#43]
## The current behavior
No Instantnodes.io on  https://solana.com/rpc. 
## The expected behavior

Please add Instant Nodes to the list of Private RPC providers on https://solana.com/rpc. 
Under both "Some free RPC providers" as we have a free plan.
            and "Private Services" - please display our details as "Instant Nodes (hybrids)"
Mainnet-beta only.
Please link our name to the following URL: https://instantnodes.io/

**Comment by catalinred** [comment]
Thank you for your submission. Our team will review it and consider the next steps.

**Comment by giftal** [comment]
@catalinred  hope you are well, 
We wanted to understand how long the review process is?

**Comment by catalinred** [comment]
@giftal I don't have an estimate at the moment, but I'll keep you updated if there's any progress. Thank you for your understanding and patience.

**Comment by catalinred** [comment]
We're currently working on updating the `CONTRIBUTING.md` file to outline the basic requirements for RPC providers.

In the meantime, if you have any resources that provide more details on your features, status reports, and documentation (such as examples, setup instructions, and guides), please feel free to share them with us.

**Comment by giftal** [comment]
Thank you @catalinred 

Features and prices: https://instantnodes.io/#prices  
Documentation and examples: https://instantnodes.io/docs/api-documenation 
Story behind the brand: https://instantnodes.io/#about

**Comment by catalinred** [comment]
Sharing that Instant Nodes has been added to RPC providers list on https://solana.com/rpc.
And just a heads up: the docs url you shared above has a typo in it so you may want to fix it.

**Comment by giftal** [comment]
Thank you. Can I ask you to join Instant Nodes into InstantNodes please?

>the docs url you shared above has a typo
Clicked several times - works well. Please advise what you see is wrong?

**Comment by catalinred** [comment]
A missing `t` in `documenation`. 
And I also updated the name to InstantNodes.

**Comment by catalinred** [comment]
fwiw, we don't use `rel="nofollow"` at this point for the resources listed on that page.

**Comment by giftal** [comment]
Thank you.

>https://instantnodes.io/docs/api-documenation
if you use it somewhere -- please correct to proper spelling (https://instantnodes.io/docs/api-documentation). We will update our site very soon.
