### ISSUE TITLE
Update to ESLint v9.0.0

### ISSUE THREAD

**Issue by catalinred** [solana-foundation/solana-com#62]
Edit: Next.js 15 introduces support for ESLint 9 now.
https://nextjs.org/blog/next-15#eslint-9-support

---

Update the ESLint dependency to v9.0.0. Currently, it appears that `next lint` does not support the latest version of ESLint.

- https://eslint.org/blog/2024/04/eslint-v9.0.0-released/
- https://github.com/vercel/next.js/issues/64409
- https://nextjs.org/docs/app/building-your-application/configuring/eslint

**Comment by devansh-m12** [comment]
can i take up this isssue ?

**Comment by catalinred** [comment]
TODO: 
investigate why silencing sass `legacy-js-api` warnings did not apply since I updated to next 15.1.0 already
