### ISSUE TITLE
Update details for Fuse wallet

### ISSUE THREAD

**Issue by metasal1** [solana-foundation/solana-com#69]
## Steps To Reproduce

solana.com/wallets

## The current behaviour

Link = fuse.io
Description = Empower your business with open-source solutions and global reach.

## The expected behaviour

Link = fusewallet.com
Description = The safest wallet for your Solana assets. 2FA. Recovery. No seed phrase.

**Comment by catalinred** [comment]
@metasal1 Even though their title mention that, to avoid "picking favorites" I will recommend to update the description to `A safe wallet for your Solana assets. 2FA. Recovery. No seed phrase.`
