### ISSUE TITLE
Add Enkrypt wallet

### ISSUE THREAD

**Issue by Abyscuit** [solana-foundation/solana-com#91]
We updated the documentation to reflect that Enkrypt wallet supports Solana network.
https://github.com/enkryptcom/enKrypt
https://www.enkrypt.com/networks/solana-wallet/
https://myetherwallet.gitbook.io/enkrypt-documentation

This is in regard to #82

**Comment by catalinred** [comment]
Thank you, we will be reviewing and get back to you!
